### ISSUE TITLE
Datasets not present in git repo appears in catalog after cleaning and rebuilding

### ISSUE THREAD

**Issue by mortenwh** [metno/catalog-rebuilder#9]
For example, I have removed `6c9689b0-5d7a-42b1-a641-1d47351bedf9.xml` from https://gitlab.met.no/mmd/mmd-xml-dev. It was in the folder `arch_0/arch_b/arch_9` but is now removed. I then cleaned both pycsw and solr. Yet, it turns up in the catalog: https://data-test.met.no/dataset/6c9689b0-5d7a-42b1-a641-1d47351bedf9

**Comment by magnarem** [comment]
Fixed in https://gitlab.met.no/s-enda/catalog-rebuilder/-/commit/7e843174ba5390abf2d6afd5fc3e4729a1edde8a

The issue was that the catalog rebuilder was cloning the repo initially, and then did git pull the next time.
I have now changed the code so that it will always clone a fresh repository.

This change have now been deployed to dev. Please test and close this issue

**Comment by mortenwh** [comment]
Yes, it seems works after rebuilding now - thanks!
